default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # username: <%= Rails.application.credentials.db[:user_id] %>
  username: root
  password: <%= Rails.application.credentials.db[:password] %>
  socket: /tmp/mysql.sock
  connection_pool: <%= ENV['MAX_CONNECTION_POOL'] || 5 %>
  host: db

development:
  <<: *default
  database: DONE_development

test:
  <<: *default
  database: DONE_test

production:
  <<: *default
  database: DONE_production